Replace Nuimo SDK with new implementation that uses BlueZ's D-Bus API
getsenic/nuimo-linux-python pull request #20
Opened 2017-02-21 14:50 UTC by larsblumberg

2017-02-22 11:58 UTC, grunskis requested changes
Left some comments.

2017-02-22 11:58 UTC, grunskis commented on nuimo.py
> +        if gesture is not None:
`gesture` will never be `None`. If the `value[0]` is not present in the dictionary then `KeyError` will be raised instead. You could set `gesture` value like this `gesture = {...}.get(value[0])` or handle `KeyError`.

2017-02-22 11:58 UTC, grunskis commented on gatt/gatt.py
> +        mac_addresses = list(filter(None.__ne__, [
You should use list comprehensions instead of `map` and `filter`

2017-02-22 11:58 UTC, grunskis commented on gatt/gatt.py
> +        filter = {'Transport': 'le'}
`filter` is a keyword in Python. It's cleaner to not use keywords as variable names

2017-02-22 11:58 UTC, grunskis commented on gatt/gatt.py
> +        if len(service_uuids) > 0:  # D-Bus doesn't like empty lists, needs to guess type
No need to check length, just `if service_uuids:` is enough

2017-02-22 11:58 UTC, grunskis commented on gatt/gatt.py
> +        bytes = [dbus.Byte(b) for b in bytes]
`bytes` is a class name from standard library. if possible, it's better to use different variable name

2017-02-22 11:58 UTC, grunskis commented on gatt/gatt.py
> +        error = errors.InProgress() if error.get_dbus_name() == "org.bluez.Error.InProgress" else errors.Unknown()
IMHO better to stick to one `if..else` style throughout the codebase

2017-02-22 11:58 UTC, grunskis commented on nuimo.py
> +            print(service.path, service.uuid)
It's better not use `print` functions in library code, but instead use `logging` library. In that way users of the library can control whether they need these log messages or not.

2017-02-22 11:58 UTC, grunskis commented on nuimo.py
> +        nuimo_service = next(service for service in self.services if service.uuid == self.NUIMO_SERVICE_UUID)
`next` will not return `None` if the the iterator is empty but throw an `StopIteration` unless you provide a default value like `next((iterator), None)`

2017-02-22 11:58 UTC, grunskis commented on nuimo.py
> +            characteristic.enable_notifications()
This would fail if characteristic is not found

2017-02-22 11:58 UTC, grunskis commented on nuimo.py
> +                [self.matrix.leds[i:i + 8] for i in range(0, 81, 8)]))
This could go into it's own function & IMHO written in a more readable way

2017-02-22 11:58 UTC, grunskis commented on nuimo.py
> +class ControllerPrintListener(ControllerListener):
Why this is in the library code? I think it belongs better in example/demo code

2017-02-22 11:58 UTC, grunskis commented on nuimo.py
> +        return not self == other
Why not `self != other`?

2017-02-22 11:58 UTC, grunskis commented on gatt/errors.py
> +class InProgress(Exception):
Usually exception subclasses have suffix `Error` or `Exception`

2017-02-22 11:58 UTC, grunskis commented on gatt/errors.py
> +		return "inprogress"
What was the reason to override these methods?

2017-02-22 11:58 UTC, grunskis commented on README.md
> +The Nuimo SDK requires [Python 3](https://www.python.org) and a recent installation of [BlueZ](http://www.bluez.org/). It is tested to work fine with BlueZ 5.43, slightly older versions should howeve
I think we should specify more specific Python version, like 3.5 since some distros provide only 3.4

2017-02-22 11:58 UTC, grunskis commented on README.md
> +On Linux the [Bluez](http://www.bluez.org/) library is necessary to access your built-in Bluetooth controller or Bluetooth USB dongle. Some Linux distributions provide a more up-to-date BlueZ package
s/BlueY/BlueZ/

2017-02-22 11:58 UTC, grunskis commented on README.md
> +1. `sudo servicectl stop blutooth`
I think it's just `service` not `servicectl`.

Also `s/blutooth/bluetooth/`

2017-02-22 11:58 UTC, grunskis commented on README.md
> +2. `cd ~`
just `cd` is enough

2017-02-22 11:58 UTC, grunskis commented on README.md
> +4. `cd bluey`
typo

2017-02-22 11:58 UTC, grunskis commented on README.md
> +6. `tar xf bluez-{{bluez_version}}.tar.xz`
`{{bluez_version}}` - looks like copy/paste mistake

2017-02-22 11:58 UTC, grunskis commented on setup.py
> +    py_modules=['nuimo'])
you have to add `modules=['gatt']` otherwise it won't be together with nuimo module

2017-02-22 11:58 UTC, grunskis commented on setup.py
> +    install_requires=['dbus-python'],
as we found out it's better to install `dbus` library with `apt` since it's dependencies are not available on pypi

2017-02-22 11:58 UTC, grunskis commented on README.md
> +7. `tar xf bluez-{{bluez_version}}.tar.xz`
`{{bluez_version}}` looks like copy/paste mistake

2017-02-22 11:58 UTC, grunskis commented on README.md
> +1. `sudo servicectl stop bluetooth`
It's just `service` or `systemctl`

2017-02-22 12:28 UTC, larsblumberg commented on nuimo.py
> +            print(service.path, service.uuid)
👍

2017-02-22 12:29 UTC, larsblumberg commented on nuimo.py
> +        nuimo_service = next(service for service in self.services if service.uuid == self.NUIMO_SERVICE_UUID)
👍 +1

2017-02-22 12:35 UTC, larsblumberg commented on nuimo.py
> +        return not self == other
According to http://stackoverflow.com/questions/1227121/compare-object-instances-for-equality-by-their-attributes-in-python#comment-22555187:

> One caveat: defining __eq__ does not automatically add support for the != operator

2017-02-23 08:56 UTC, grunskis approved these changes

2017-02-23 14:42 UTC, grunskis commented on gatt/gatt.py
> +                raise errors.NotReady("Bluetooth adapter not ready. Run 'hciconfig " + self.adapter_name + " up'.")
Why you don't want to use one of the many string interpolation methods that Python has instead of `+`? :)

2017-02-23 17:19 UTC, merged